In [3]:
import numpy as np


In [68]:
class Model:
    def __init__(self, y ,r, n, lr,reg,j ):
        self.y=y
        self.r=r
        self.n=n
        self.m,self.u=self.y.shape
        self.lr=lr
        self.reg=reg
        self.j=j
        
    def initialize(self):
        self.theta=np.random.rand(self.u,self.n)
        self.X=np.random.rand(self.m,self.n)
        
    def cost(self):
        self.J= np.sum(np.sum(np.square(((self.X @ self.theta.T)-self.y)*self.r)))/2
        self.J+=self.reg/2 * (np.sum(np.sum(np.square(self.X)))+np.sum(np.sum(np.square(self.theta))))
        
        self.xgrad=((self.X@self.theta.T - self.y)*self.r)@self.theta + self.reg*self.X
        self.thetagrad= ((self.X@self.theta.T - self.y)*self.r).T @ self.X + self.reg*self.theta
        
    def graddescent(self):
        for i in range(self.j):
            self.cost()
            self.X=self.X-self.lr/self.m * self.xgrad
            self.theta=self.theta-self.lr/self.m * self.thetagrad
            print(f"Iteration {i}: Cost {self.J}\n")
            if(i%9==0):
                print(f"X={self.X}\n\n t= {self.theta}\n\n, pred={self.X@self.theta.T}\n\n")
            
            

In [69]:
y=np.array([[5,0 , 5],
            [4, 1, 0],
            [2, 5 ,0],
            [0, 3, 3]])
r=np.array([[1,0 , 1],
            [1, 1, 0],
            [1, 1 ,0],
            [0, 1, 1]])
m=Model(y,r, 3,0.1, 0.01, 100)
m.initialize()

m.graddescent()

Iteration 0: Cost 32.83180517660517

X=[[1.08307565 0.91464067 0.83675607]
 [0.67715026 0.34029453 0.0201028 ]
 [0.761192   0.37238314 0.19322716]
 [0.9384438  0.09195189 0.30209151]]

 t= [[0.73299252 1.04547553 0.17191221]
 [0.95630379 0.35851238 0.4580304 ]
 [0.85507637 0.51822211 0.87231528]]

, pred=[[1.89396937 1.74691907 2.13001452]
 [0.85557159 0.77876886 0.77289932]
 [0.9804836  0.94993867 1.01240947]
 [0.83593895 1.06877035 1.11361166]]


Iteration 1: Cost 26.324036088815685

Iteration 2: Cost 19.93930009562782

Iteration 3: Cost 14.384297791206297

Iteration 4: Cost 10.17118321165824

Iteration 5: Cost 7.3891654957231525

Iteration 6: Cost 5.754552257330377

Iteration 7: Cost 4.856282428375784

Iteration 8: Cost 4.357163541453545

Iteration 9: Cost 4.05004595746058

X=[[1.6292235  1.41474879 1.17765854]
 [0.96604069 0.86890655 0.08078448]
 [1.49348717 0.57264701 0.5228218 ]
 [1.37471938 0.30103542 0.59449958]]

 t= [[1.36014572 1.56347624 0.42168377]
 [1.73867305 0.61370655 