In [2]:
import numpy as np
import random as r

In [143]:
class Model:
    def __init__(self,X, k,niter,cent):
        self.X=X
        self.m,self.n=X.shape
        self.idx=np.zeros([self.m,1])
        self.k=k
        self.niter=niter
        self.centroids=cent
        
    def ClusterInit(self):
        self.centroids=np.zeros([self.k,self.n])
        for i in range(self.k):
            self.centroids[i]=self.X[r.randint(0,self.m-1)]
    def AssignToCluster(self):
        dist=np.zeros([self.m,self.k])
        for i in range(self.k):
            dist[:,i]=np.sum(np.square(self.X-self.centroids[i,:]), axis=1).T
        self.idx=np.reshape(np.argmin(dist, axis=1) , [self.m,1])
        return self.idx
    def NewPosition(self):
        nc=np.zeros([self.k,self.n])
        
        for i in range(self.k):
            x=0
            for j in range(self.m):
                if self.idx[j]==i :
                    x+=1
                    nc[i,:]+=self.X[j,:]
            if x!=0:
                nc[i,:]=nc[i,:]/x            
        self.centroids=nc
#         print(f"{self.centroids}")
            
       
    
    def train(self):
#         self.ClusterInit()
        print(f"{self.centroids}")
        for i in range(self.niter):
            print(f"Iteration {i}/100: {self.centroids}")
            print(self.AssignToCluster())
            self.NewPosition()
        return self.centroids, self.idx   

In [144]:
c=np.zeros([2,2])
# c[0]=r.randint(0,)
a=np.array([[7, 8], [9, 8], [8, 6], [0, 8],[1,4]])
c=np.array([ [7,6],[0,9]])
dist=np.zeros([4,2])
k=2
n=2
m=4
# for i in range(2):
#     dist[:,i]=np.sum(np.square(a-c[i,:]), axis=1).T

# idx=np.reshape(np.argmin(dist, axis=1) , [4,1])
# nc=np.zeros([k,n])
# # x=0
# for i in range(k):
#     if(i!=0):
#         nc[i-1,:]=nc[i-1,:]/x
#     x=0
#     for j in range(m):
#         if idx[j]==i :
#             x+=1
#             nc[i,:]+=a[j,:]
# c=nc
# dist,idx,c
m= Model(a,2,100,c)
c,idx=m.train()
c,idx

[[7 6]
 [0 9]]
Iteration 0/100: [[7 6]
 [0 9]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 1/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 2/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 3/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 4/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 5/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 6/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 7/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 8/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 9/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [0]
 [1]
 [1]]
Iteration 10/100: [[8.         7.33333333]
 [0.5        6.        ]]
[[0]
 [0]
 [

(array([[8.        , 7.33333333],
        [0.5       , 6.        ]]),
 array([[0],
        [0],
        [0],
        [1],
        [1]], dtype=int64))