In [2]:
import numpy as np

In [66]:
class PCA:
    def __init__(self,X,k):
        self.X=X
        self.k=k
        self.m, self.n = X.shape
        
    def Normalize(self):
        mu= np.sum(self.X,axis=0)/self.m
        self.X=(self.X-mu)
        sigma= np.sqrt(np.sum(np.square(self.X), axis=0)/(self.m-1))
        self.X=(self.X)/sigma
        return self.X, mu, sigma
    
    def svd(self):
        cov=np.dot(self.X.T,self.X)/self.m
        U, S, V = np.linalg.svd(cov)
        self.U=U[:, :self.k]
        self.var= np.sum(S[:self.k])/np.sum(S)
        self.S=np.diag(S)
        return self.U,self.S,self.var
    
    def ProjectData(self):
        self.Xk=np.dot(self.X, self.U)
        return self.Xk
    def RecoverData(self):
        self.Xr= np.dot(self.Xk, self.U.T)
        return self.Xr
    def Run(self):
        Xnorm, mu, sigma=self.Normalize()
        U,S,var=self.svd()
        Xk=self.ProjectData()
        Xr=self.RecoverData()

        print(f"{Xnorm}\n{mu}\n{sigma}\n{U}\n{S}\n{Xk}\n{Xr}\n{var}")

In [68]:
X=np.array([[1,2,5,6],[3,6,4,3],[1,3,5,4], [9,7,8,9]])
m=PCA(X,3)
# Xn, mu,sigma = m.Normalize()
# X,Xn, mu,sigma
# cov=np.dot(X.T,X)/3
# U, S, V = np.linalg.svd(cov)
# cov,U,np.diag(S),V
# np.dot(np.dot(X,U[:,:1]), U[:,:1].T)
m.Run()

[[-0.66033818 -1.05021006 -0.28867513  0.18898224]
 [-0.13206764  0.63012604 -0.8660254  -0.94491118]
 [-0.66033818 -0.63012604 -0.28867513 -0.56694671]
 [ 1.452744    1.05021006  1.44337567  1.32287566]]
[3.5 4.5 5.5 5.5]
[3.7859389  2.38047614 1.73205081 2.64575131]
[[-0.55254033 -0.21776311  0.10119969]
 [-0.41178267 -0.75614634  0.08261895]
 [-0.53199533  0.32795584 -0.75900764]
 [-0.49205202  0.52274937  0.63784021]]
[[2.36070416e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.11301688e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.79941505e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.12498565e-16]]
[[ 0.85790651  0.94202744  0.18605383]
 [ 0.73916464 -1.22567785  0.09331271]
 [ 1.05687955  0.22922106 -0.26140114]
 [-2.6539507   0.05442935 -0.0179654 ]]
[[-0.66033818 -1.05021006 -0.28867513  0.18898224]
 [-0.13206764  0.63012604 -0.8660254  -0.94491118]
 [-0.66033818 -0.63012604 -0.28867513 -0.56694671]
 [ 1.452744